### ISSUE TITLE
Tutorial solution error:  error in IOstream "OSHA1stream.sinkFile_" for operation Ostream& operator<<(Ostream&, const char)

### ISSUE THREAD

**Issue by ZoroOP** [fppimenta/rheoTool#113]
I am using OpenFOAM 9, and successfully installed OpenFOAM (icoFoam solver runs well in the cavity tutorial) and rheoTool.

But when I solving of90/tutorials/rheoFoam/Channel/Oldroyd-BLog, a error appears.

The error prompt is :

pfg@kubuntu:~/rheoTool/of90/tutorials/rheoFoam/Channel/Oldroyd-BLog$ rheoFoam
/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Version:  9
     \\/     M anipulation  |
\*---------------------------------------------------------------------------*/
Build  : 9
Exec   : rheoFoam
Date   : Jun 19 2023
Time   : 23:19:37
Host   : "kubuntu"
PID    : 4658
I/O    : uncollated
Case   : /home/pfg/rheoTool/of90/tutorials/rheoFoam/Channel/Oldroyd-BLog
nProcs : 1
sigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Create mesh for time = 0

SIMPLE: No convergence criteria found

SIMPLE: No convergence criteria found

SIMPLE: Operating solver in transient mode with 1 outer corrector
SIMPLE: Operating solver in PISO mode

Reading field p

Reading field U

Reading/calculating face flux field phi

Using openFoamSolver solver for p
Using openFoamSolver solver for U
Selecting constitutive equation Oldroyd-BLog
Selecting thermoFunction: Constant
Selecting thermoFunction: Constant
No MRF models present

No fvModels present
No fvConstraints present
Courant Number mean: 0.000125 max: 0.00625

Starting time loop

--> FOAM FATAL IO ERROR: 
error in IOstream "OSHA1stream.sinkFile_" for operation Ostream& operator<<(Ostream&, const char)

file: OSHA1stream.sinkFile_ at line 0.

    From function virtual bool Foam::IOstream::check(const char*) const
    in file db/IOstreams/IOstreams/IOstream.C at line 96.

FOAM exiting

pfg@kubuntu:~/rheoTool/of90/tutorials/rheoFoam/Channel/Oldroyd-BLog$

**Comment by fppimenta** [comment]
https://github.com/OpenFOAM/OpenFOAM-9/issues/12

**Comment by OP-ACE** [comment]
Thanks  for your reply. I am a little consued here. 
As mentioned in your link, "Simply updating your OpenFOAM version should do the trick", so I should upgrade OpenFoam to v10?
But rheoTool is still compatible with v9 now.

**Comment by fppimenta** [comment]
Updating to the last patch of of90 or downgrading the compiler version.

**Comment by OP-ACE** [comment]
You may find this hard to believe, but this is the first time I have heard of the patched version of OpenFoam. I have always naively assumed that v9 marked on the website must be the latest v9. In any case, thank you so much for your patient explanation. Thank you for your contributions to open source. I hope that one day I can reach your level and contribute to open source as well, however slow a learner I may be.

**Comment by lip-o** [comment]
An alternative solution - if you need to stick to an older version - is to re-build from scratch using an older gcc version. I had the same error with OpenFOAM v8 and gcc13.3.0 and could resolve it by using gcc9.3.0. For more details of the problem also refer to the commit notes: https://github.com/OpenFOAM/OpenFOAM-9/commit/b0c15bebd37142f3902901ed5e9a60e33ed456eb
