### ISSUE TITLE
Error in compiling Rheotool master

### ISSUE THREAD

**Issue by sasankheirandish** [fppimenta/rheoTool#13]
Dear Francisco Pimenta,
I want to compile Rheotool master version 3.0 on Ubuntu 18.04. I installed Eigen library successfully ,however I will be faced with this error:

Allwmake /home/kiakaren/rheoTool-master/of60/src
Allwmake /home/kiakaren/rheoTool-master/of60/src/libs
+ wmake libso constitutiveEquations
wmake libso constitutiveEquations
/opt/openfoam6/wmake/wmake: line 410: make: command not found
/opt/openfoam6/wmake/wmake: line 413: make: command not found
wmake error: file 'Make/linux64GccDPInt32Opt/sourceFiles' could not be created in /home/kiakaren/rheoTool-master/of60/src/libs/constitutiveEquations

Could you please help me with this problem?
Best regards
Sasan kheirandish

**Comment by fppimenta** [comment]
The error tells you that make (used by openfoam's wmake) is not installed in your system (or it is there but in a strange place). You probably missed something while installing openfoam. I suggest to reinstall openfoam and try again. 

Please note that the most recent version of rheoTool is 4.0 and it is the one that you can currently find in master/. You can however install 3.0 by accessing older commits or, better, the latest release, which in fact corresponds to 3.0. I would however suggest 4.0 (there is nothing in 3.0 that you cannot do in 4.0).
