### ISSUE TITLE
question about RheoInterFoam

### ISSUE THREAD

**Issue by sasankheirandish** [fppimenta/rheoTool#16]
Dear Francisco Pimenta
I am using rheoInterFoam solver for viscoelastic multi-phase fluids. In constitutive properties that is in constant folder, there is a parameter named uTauCoupling , which can be set as true or false.
what does utaucoupling do in viscoelastic fluids?
Best regards

**Comment by fppimenta** [comment]
_uTauCoupling_  has been replaced by _stabilization_  keyword since version 2.0 and allows you to select the stabilization method of the momentum equation related with the extra-stress tensor. See sections 4.1.4 and 5.1.1/constant of the current version of the user-guide.
