### ISSUE TITLE
Error while compiling rheotool

### ISSUE THREAD

**Issue by emcar093** [fppimenta/rheoTool#19]
Dear Francesco Pimenta, 
I tried to compile rheoTool with OpenFoam v7 on Ubuntu 19.10 and while compiling the following error appeared:

constitutiveEqs/otherModels/ML-IKH/ML_IKH.C:254:41: error: ‘const Mesh’ {aka ‘const class Foam::fvMesh’} has no member named ‘solver’; did you mean ‘Foam::dictionary Foam::solution::solvers_’? (not accessible from this context)
  254 |           lambdaIEqn.solve(phi().mesh().solver("lambdaI"));
      |                                         ^~~~~~
In file included from /opt/openfoam7/src/finiteVolume/lnInclude/fvSolution.H:37,
                 from /opt/openfoam7/src/finiteVolume/lnInclude/fvMesh.H:56,
                 from /opt/openfoam7/src/finiteVolume/lnInclude/volMesh.H:42,
                 from /opt/openfoam7/src/finiteVolume/lnInclude/volFields.H:38,
                 from lnInclude/constitutiveEq.H:40,
                 from constitutiveEqs/otherModels/ML-IKH/ML_IKH.H:36,
                 from constitutiveEqs/otherModels/ML-IKH/ML_IKH.C:27:
/opt/openfoam7/src/OpenFOAM/lnInclude/solution.H:74:20: note: declared private here
   74 |         dictionary solvers_;
      |                    ^~~~~~~~
make: *** [/opt/openfoam7/wmake/rules/General/transform:26: Make/linux64GccDPInt32Opt/constitutiveEqs/otherModels/ML-IKH/ML_IKH.o] Error 1

Could you please help me with this problem?
Best regards

**Comment by fppimenta** [comment]
There is still not a rheoTool version for OpenFOAM v7. The most recent you can use is OpenFOAM v6. The new version compatible with OpenFOAM v7 will come soon.
