### ISSUE TITLE
Multiphase flow solver RheoTool

### ISSUE THREAD

**Issue by sarmadip** [fppimenta/rheoTool#20]
Hi,
I am wondered if there is a solver similar to multiphaseinterfoam of openfoam in rheotool. In fact, I am trying to simulate 3-layer viscoelastic+Newtonian flow.
Thanks

**Comment by fppimenta** [comment]
No, there is a only two-phase flow solver.

**Comment by sarmadip** [comment]
Thanks for quick reply
