### ISSUE TITLE
Error in installing PETSc 

### ISSUE THREAD

**Issue by basharz** [fppimenta/rheoTool#22]
Hi, 
I hope you are keeping well. 
I have been trying to compile Rheotool onto my OpenFOAM v.6 on ubuntu 18.04. I get an error when doing ./InstallPetsc, I get the configure is confusing and doesn't know what compiler to select and use (Shown in the pic). 
Your help is much appreciated. (I am new to coding) 

![PETSc error ](https://user-images.githubusercontent.com/65765906/82661176-6f1a3b80-9c23-11ea-8a9c-c03a2a1ee070.png)

**Comment by fppimenta** [comment]
This is not the source of the problem, but will probably give errors later: you are using OF 6.0, but PETSc is being installed with openmpi from thirdParty of openfoam v1812. You can't do that, unless OF 6.0 is also compiled with the same openmpi, which I guess is not the case. Therefore, you should first fix this versioning issue (create an alias for each version and call the alias for of60 before compilling PETSc). This might be useful: 

https://openfoamwiki.net/index.php/Installation/Working_with_the_Shell#Using_aliases_to_help_manage_multiple_OpenFOAM_versions

**Comment by basharz** [comment]
Thank you for your quick response. I have used the link you sent, I still get the same error. Is the alias I done correct in my .bashrc file? (error included below) 
![creating alias ](https://user-images.githubusercontent.com/65765906/82692240-42801700-9c57-11ea-89bb-6850ff1e0a0e.png)
![PETSc error](https://user-images.githubusercontent.com/65765906/82692247-47dd6180-9c57-11ea-90ea-ab55d20b9e5a.png)

**Comment by fppimenta** [comment]
You also need to create an alias for of1812 (the same as you did for of60), otherwise it will be the default option (which might not be bad, but let's enclose it for now while debugging):

in your ~/.bashrc replace line    source home/.../Openfoam1812...     by     alias of1812='source home/.../Openfoam1812...'        

After you do that, if everything is fine,  you should get an error when you open a new terminal and type e.g. 

icoFoam 

If this is so, open a new terminal to compile Petsc, type your alias

of60

and before calling ./InstallPetsc get some env variables:

echo $FOAM_MPI
echo $FOAM_LIBBIN
echo $MPI_ARCH_PATH 

What is the result of the previous echo's? Then call ./InstallPetsc.

**Comment by basharz** [comment]
Thank you very much, I will try this now

**Comment by basharz** [comment]
Everything you recommended before ./InstallPetsc was working, but when I ran ./InstallPetsc I get the same error. My echo's before running are shown below. 
![echo ](https://user-images.githubusercontent.com/65765906/82696534-12d50d00-9c5f-11ea-96a9-19be738f6931.png)

**Comment by fppimenta** [comment]
Something seems to be wrong with your openfoam 6.0 installation. As you see, $FOAM_LIBBIN is returning you a path to openfoam 1812.

Ok, I get it, your alias of60 is wrong, as it is pointing to openfoam 1812. It should point to openfoam 6.0. Two examples (do not copy them; adjust them to your own paths):

 alias of60='source /opt/**openfoam6**/etc/bashrc'
 alias of1812='source ~/OpenFOAM/OpenFOAM-v1812/etc/bashrc'

So you will know when you are ready to compile Petsc, when before doing that, you will be able to run any tutorial from **openfoam 6.0**. If the tutorial works, the installation will run fine.

**Comment by basharz** [comment]
All of my tutorials are in OpenFOAM-v1812. Please see the images below (This is my ubuntu directory after I done the change you recommended). Should I move the Eigen and PETSc files to the third-party folder in OpenFOAM. 
![jadzo-v1812](https://user-images.githubusercontent.com/65765906/82710153-1d50d000-9c7a-11ea-9f52-5ea8c8808c56.png)
![OpenFOAM-v1812](https://user-images.githubusercontent.com/65765906/82710157-1fb32a00-9c7a-11ea-8c90-1e34bd229336.png)
![path](https://user-images.githubusercontent.com/65765906/82710159-22158400-9c7a-11ea-8f46-a121b0a8b754.png)
![ThirdParty-v1812](https://user-images.githubusercontent.com/65765906/82710164-2477de00-9c7a-11ea-8d05-4dd551f9cbf7.png)

**Comment by basharz** [comment]
As seen in the pics. Should I move of60 (In rheotool-master) into my OpenFOAM-v1812 folder? 
![Ubuntu](https://user-images.githubusercontent.com/65765906/82711271-c8fb1f80-9c7c-11ea-82c3-b6bcf885ea93.png)
![OpenFOAM-v1812-2](https://user-images.githubusercontent.com/65765906/82711275-cdbfd380-9c7c-11ea-9818-535f74f33a6b.png)
![of60](https://user-images.githubusercontent.com/65765906/82711280-d1535a80-9c7c-11ea-9fb4-cb157c65f345.png)

**Comment by fppimenta** [comment]
Are you sure that openfoam 6.0 (https://openfoam.org/version/6/) is installed in your system?

**Comment by basharz** [comment]
I installed OpenFOAM from this link (https://sourceforge.net/projects/openfoam/files/v1812/OpenFOAM-v1812-windows10.tgz/download?use_mirror=netcologne&r=https%3A%2F%2Fwww.openfoam.com%2Fdownload%2Finstall-windows-10.php&use_mirror=netcologne) 
And followed this tutorial, (https://www.youtube.com/watch?v=cUbC0MrkiOA&t=792s).
I managed to download the version, shown in OpenFOAM (The pic). Do you think this version should fix the problem?
<img width="702" alt="Screenshot 2020-05-22 at 23 23 53" src="https://user-images.githubusercontent.com/65765906/82713600-56da0900-9c83-11ea-9c04-c0e75defc406.png">

**Comment by fppimenta** [comment]
Ok, so you don't have openfoam 6.0 installed and I guess you misunderstood my comments above about the alias.

There are essentially 3 major flavours of openfoam, and they are all different (though similar): 

- openfoam.org (https://openfoam.org/)
- openfoam.com (https://openfoam.com/)
- foam-extend (https://openfoamwiki.net/index.php/Installation/Linux/foam-extend-4.1)

If you have interest, here is some info about them: https://www.cfd-online.com/Forums/openfoam/197150-openfoam-com-versus-openfoam-org-version-use.html

Rheotool was built to work with openfoam.org and foam-extend, but not with openfoam.com. The version you have (1812, and any version with 4 numbers) is from openfoam.com, thus it will not compile, and this has nothing to do with Petsc. Therefore, either install a version from openfoam.org or foam-extend. I perhaps suggest you going to openfoam.org, as it should be easier to get it installed. Either 

 -version 6: https://openfoam.org/version/6/ 

or 

-version 7: https://openfoam.org/version/7/ 

will work (get the most recent one, 7, if it is indifferent for you).

**Comment by basharz** [comment]
Thank you for your help. I shall download version 7, and let you know the outcome. Sorry about the misinformation from my end.

**Comment by basharz** [comment]
Thanks for your help. I have managed to download rheoTool. 

I tried to run the cylinder tutorial (In pic), but I am unsure if I am doing it wrong. 
![running tutorial](https://user-images.githubusercontent.com/65765906/82719005-81858b00-9c9e-11ea-9d93-0c2f6598aa17.png)
![tutorial](https://user-images.githubusercontent.com/65765906/82719010-89ddc600-9c9e-11ea-8d90-0ef4b70e482a.png)

**Comment by basharz** [comment]
As seen in the pic, the RheoFoam is in my bin. Is the solution to link the commands to my ubuntu, by putting source /home/.../OpenFOAM/etc/bashrc in my bashrc? 
bashrc (Included in pic)
![bashrc](https://user-images.githubusercontent.com/65765906/82726385-ab10d780-9cdb-11ea-92bc-c71e4f97e96b.png)

![bin ](https://user-images.githubusercontent.com/65765906/82726246-997b0000-9cda-11ea-97ba-fde1791d7911.png)

**Comment by basharz** [comment]
I think I’ve found the problem

**Comment by fppimenta** [comment]
The solution to your problem is in section 2.4.4 of the user-guide, in the note about the alias. 
If the problem persists, printscreen your ~/.bashrc.

**Comment by basharz** [comment]
I got it to work. Thank you for your help!
