### ISSUE TITLE
psi contribution in NernstPlanckCoupled

### ISSUE THREAD

**Issue by syavash20** [fppimenta/rheoTool#23]
Hi,

I cannot find the contribution of psi potential in species equation defined in NernstPlanckCoupled. Also, there is not a Poisson equation for psi as in the segregated solver (laplacian(psi)==-rhoE). Am I missing something? (using rheoTool for OpenFOAM 6).

Kind regards,
syavash

**Comment by fppimenta** [comment]
For the coupled solver,

// psi_psi
   cps_->insertEquation
   (
    psi_.name(),
    psi_.name(),
    fvm::laplacian(psi_)
   ); 

and 

 // psi_ci 
     cps_->insertEquation
     ( 
       psi_.name(),
       ci.name(),  
       fvm::Sp(species_[i].zi()*FK_/(relPerm_*epsilonK_), ci)	
     );  

define psi equation. The contribution of phiE (if defined) keeps segregated.

**Comment by syavash20** [comment]
> For the coupled solver,
> 
> // psi_psi
> cps_->insertEquation
> (
> psi_.name(),
> psi_.name(),
> fvm::laplacian(psi_)
> );
> 
> and
> 
> // psi_ci
> cps_->insertEquation
> (
> psi_.name(),
> ci.name(),
> fvm::Sp(species_[i].zi()*FK_/(relPerm_*epsilonK_), ci)
> );
> 
> define psi equation. The contribution of phiE (if defined) keeps segregated.

Thank you. It's clearly me being unfamiliar with the coupled solver. Do you have any paper or document which gives a thorough elaboration on implementing the coupled method and its functions. for instance cps_?

**Comment by fppimenta** [comment]
It's in the user-guide and here:

https://arxiv.org/pdf/1904.02138

**Comment by EliHoenig** [comment]
Hello, thank you for this amazing work. A quick follow up on the above question. In the psi_ci equation, how are the ci terms being summed (so we get total concentration as opposed to the concentration of a given species)? This is done explicitly in the NernstPlanck.C file, but it's hard for me to figure out in NernstPlanckCoupled.C.

**Comment by fppimenta** [comment]
That is done here: 
https://github.com/fppimenta/rheoTool/blob/56c2701636e6eb59dc51799fd0636805be23510d/of70/src/libs/EDFModels/models/NernstPlanck/NernstPlanckCoupled/NernstPlanckCoupled.C#L351

More info in the paper above.

**Comment by EliHoenig** [comment]
Okay, thank you for your quick response. I will spend more time with the paper -- I saw the line referenced, but didn't understand where the summation comes in. I guess you're loading up the sparse matrix and the summation follows from the resulting matrix algebra.
