### ISSUE TITLE
Tutorial - Flow around a Cylinder 

### ISSUE THREAD

**Issue by basharz** [fppimenta/rheoTool#24]
Hi, 

I hope you are keeping well. 

I am trying to run the flow around a cylinder tutorial, I am following the steps but I am getting an error (when I run rheoFoam). The rest of the tutorials I tried worked. 

Please see attached error. Can you advise on what I can do, your help is much appreciated. 
![Running RheoTool](https://user-images.githubusercontent.com/65765906/86899550-13880c80-c102-11ea-914b-d76430e24117.PNG)

Best Regards

**Comment by fppimenta** [comment]
I suppose you are following the steps in the user-guide. Step 2 is outdated (it was based on openfoam 2.2.2) and should be:

mirrorMesh -noFunctionObjects -overwrite 

The Allrun script provided in that directory is, however, up-to-date (this is what we ensure in each release). It will take some time to rewrite the practical sections of the user-guide based on a more recent version of openfoam.

**Comment by basharz** [comment]
Thank you very much Francisco for your help. Yes, I was following the user guide, I'll try what you recommended.

Best Regards,
Bashar
________________________________
