### ISSUE TITLE
Flow past a Cylinder 

### ISSUE THREAD

**Issue by basharz** [fppimenta/rheoTool#25]
Hi, 

I hope you are keeping well. 

Can Boger, Newtonian and shear thinning elastic fluids be modelled using rheoFoam. If not can the constitutiveProperties be changed to  transportProperties of various fluids such as Newtonian (from the OpenFOAM user guide)? 

Also, how can the drag coefficient/Strouhal number be plotted in post-processing. 

Your help is much appreciated, thanks in advance.

**Comment by fppimenta** [comment]
All the three kind of fluids you mention can be simulated with rheoFoam. See the user-guide and the tutorials for how to select the constitutive equations.
