### ISSUE TITLE
downloadEigen script failing due to 404 error

### ISSUE THREAD

**Issue by thebhatman** [fppimenta/rheoTool#26]
When I try to download eigen using the downloadEigen script in of60, it gives a 404 error and the bitbucket link for the eigen repository is either moved or not working. Can somebody help me install Eigen for Rheotool?

**Comment by thebhatman** [comment]
Okay, I realized the bitbucket eigen repo has been migrated to gitlab. So I downloaded eigen 3.2.9 from gitlab and followed the same commands as in the script downloadEigen to set the EIGEN_RHEO variable and move the Eigen directory to the appropriate location.

**Comment by fppimenta** [comment]
Thanks for reporting this bug. 

Fixed by commit 56c2701 .
