### ISSUE TITLE
Error in installing PETSc when configure

### ISSUE THREAD

**Issue by wxyhappy0201** [fppimenta/rheoTool#29]
Hi!
I have been trying to compile Rheotool onto my OpenFOAM v.7 on ubuntu 18.04. I get an error when doing ./InstallPetsc,
and my openFoam version is v.7 and there are only one version of openFoam on my ubuntu 18.04
also my gcc -v is 64 bit and gfortran is also 64 bit .
here are the error messages:
TESTING: checkFortranNameMangling from config.compilers
Unknown Fortran name mangling: Are you sure the C and Fortran compilers are compatible?
  Perhaps one is 64 bit and one is 32 bit?

![image](https://user-images.githubusercontent.com/30213546/93442658-a911fa80-f902-11ea-8896-072821617d7d.png)

**Comment by fppimenta** [comment]
What is the complete output of:
  gcc -v
  gfortran -v
  mpifort -v
  mpicc -v
  which gcc
  which gfortran
  which mpifort
  which mpicc
  which mpicxx

**Comment by wxyhappy0201** [comment]
1、gcc -v
![image](https://user-images.githubusercontent.com/30213546/93495830-24929c80-f941-11ea-8228-8c739eeb164c.png)
2、gfortran -v
![image](https://user-images.githubusercontent.com/30213546/93495903-35431280-f941-11ea-8c55-7166181885d3.png)
3、mpifort -v
![image](https://user-images.githubusercontent.com/30213546/93495970-4724b580-f941-11ea-80b1-244458ba3143.png)
4、mpicc -v
![image](https://user-images.githubusercontent.com/30213546/93496051-57d52b80-f941-11ea-8f69-5b0951421df0.png)
5、
![image](https://user-images.githubusercontent.com/30213546/93496212-881cca00-f941-11ea-805a-13cb2d1d0c47.png)

**Comment by fppimenta** [comment]
You are not showing the final output (namely the version) of mpifort -v, but from what I can see you have gcc 7.x, but gfortran 5.x. The mismatch between versions is the source of the error. I guess you did something in the past to have different versions  for gcc and gfortran, as this is not the standard when installing a fresh UB 18.04. It is easy to get gfortran-7 (it is perhaps already installed) and switch between versions of gfortran. However, you need to have openmpi compiled with that same gfortran version and this can be tricky and affect other apps. The immediate options that I can see:
 - set the correct sym link to gfortran-7 and openmpi;
 - not sure if upgrading the OS would fix the issue (it is perhaps a bad idea if you want to keep your other apps safe);
 - create a virtual machine and make a fresh install of the OS and openfoam. If possible, this is the easiest and most effective option.
 - change Petsc configure options to avoid the need of fortran compilers. This option is also effective and easy, but you will not be able to use e.g. MUMPS solvers from rheoTool (also need to change the tutorials that use it), which is a direct matrix solver. If this is ok for you, then open file 'installPetsc' and replace line 130 by this (it is a single line):

./configure --with-mpi-dir=$mpiDir --with-debugging=0 --download-hypre --download-parmetis --download-metis --download-ptscotch --with-precision=double --with-shared-libraries=1 --with-scalar-type=real --with-fc=0  --with-fortran-bindings=0 --with-cc=$mpiCC --with-cxx=$mpiCXX CXX_LINKER_FLAGS=-Wl,--no-as-needed CFLAGS="-g -O2 -fPIC -fstack-protector-strong -Wformat -Werror=format-security" CXXFLAGS="-g -O2 -fPIC -fstack-protector-strong -Wformat -Werror=format-security"  CPPFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2" LDFLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro" MAKEFLAGS=w

**Comment by wxyhappy0201** [comment]
I got it ,Thank you for your help!
