### ISSUE TITLE
OpenFOAM 6 support not included in release v2.0

### ISSUE THREAD

**Issue by gcapes** [fppimenta/rheoTool#3]
The installation instructions don't make it obvious that I need to clone the repo in order to get the `of60/src` directory.

**Comment by fppimenta** [comment]
As explained in the changelog file or the changelog section in the user-guide, support for of60 only became available from rheoTool version 3.0. Therefore, tag v2.0 (version 2.0) is missing this support. 

If you want to use the most updated version of rheoTool, you should clone or download the repository (it will automatically point to the latest commit). Releases are tags to older versions (they are created once a new versions comes out) and shall not be used for such purpose. I know this can sound strange.

**Comment by gcapes** [comment]
It does sound strange to only 'release' a version once you've released the next one. I might not be the only person who thinks that they should download an official release in order to be using stable code. I'm just making suggestions on how to make the documentation more user friendly.

**Comment by fppimenta** [comment]
Yes, it is indeed not the 'usual way' to do it. We will add a note in the user-guide or readme clarifying the purpose of releases (tags to older versions). The newest commit in the master branch is the stable code.
