### ISSUE TITLE
CFL number control

### ISSUE THREAD

**Issue by zhukansi** [fppimenta/rheoTool#30]
Hi:
I have a question about CFL number.The case of Nerstblanck in ICEO has a very small CFL number and the result gets worse  if I increase the number.Normally,we set the CFL to 2or1,but why it's so small in our case?Is there any theory about it?

**Comment by fppimenta** [comment]
In low Re flows, the Courant number is usually not very useful (I rarely look to it), because there are more restrictive conditions for stability. In EO, for example, the diffusive time-scale of ionic species is typically the most stringent condition.

**Comment by zhukansi** [comment]
> In low Re flows, the Courant number is usually not very useful (I rarely look to it), because there are more restrictive conditions for stability. In EO, for example, the diffusive time-scale of ionic species is typically the most stringent condition.

I got it! Thanks.
