### ISSUE TITLE
Solving two equations with a coupledSolver

### ISSUE THREAD

**Issue by FoamScience** [fppimenta/rheoTool#34]
> This issue is not directly related to one of your solvers, but it's related to the interface to PETsc

Hi,
First of all, thanks for this marvelous piece of software you're maintaining!

I'm attempting to solve a coupled system (for two scalars T1, T2, to which I already have a working segregated solver):

<img src="https://render.githubusercontent.com/render/math?math=\frac{\partial }{\partial t} (C_1 T_1) %2B  \nabla \cdot (M_1 (\gamma_1 \nabla g- \nabla T_2)) %2B S_{1(T_2)} = 0">

<img src="https://render.githubusercontent.com/render/math?math=\frac{\partial }{\partial t} (C_2 T_1) %2B  \nabla \cdot (M_2 (\gamma_2 \nabla g- \nabla T_2)) %2B S_{2(T_2)} = 0">

From what I gather from `rheoFoam.C`, I should:
```cpp
autoPtr<coupledSolver> cs (new coupledSolver(...));
cs->insertMesh(mesh);
cs->insertField(T1);
cs->insertField(T2);

// Start time loop

// S1 and S2 are matrices for T2
// Define equations
auto T1Eqn( fvm::ddt(C1, T1) + fvc::(phi1G) );              // gravity treated explicitely
auto T2InT1Eqn ( - fvm::laplacian(-M1, T2)  + S1 );
cs->insertEquation(T1.name(), T1.name(), T1Eqn);
cs->insertEquation(T1.name(), T2.name(), T2InT1Eqn);

// Define T2Eqn and T1InT2Eqn similarly and insert them into the matrix
auto T2Eqn( fvm::laplacian(-M2, T2) + fvc::(phi2G) + S2);
auto T1InT2Eqn ( - fvm::ddt(C2, T1)  );
cs->insertEquation(T2.name(), T2.name(), T1Eqn);
cs->insertEquation(T2.name(), T1.name(), T1InT2Eqn);

// Then
cs->solve();

// End time loop
```

But this doesn't really work; So I decided to check here if the interface is general enough to support such circumstances.

1. I'm not sure about coupling `ddt` terms in this way (Should it "just work"?)
2. My (working) segregated solver actually solves Eq1 then (Eq1+Eq2) but I don't think it's relevant

> I'm new to PETsc. Appologies if this seems trivial

**Comment by fppimenta** [comment]
The time derivative of the 2nd eq seems a little strange. Should it be in T2? Assuming that the equations are correctly typed, there are wrong signs in the eqs inserted. Are there additional coupling terms in sources S1_2?

**Comment by FoamScience** [comment]
Thanks for the super-quick reply.

1. The time derivative of the 2nd eq is indeed in "T1"
2. No additional coupling terms in S1 and S2. They are matrices for T2

Should S1 in `T2InT1Eqn` have a negative sign? `auto T2InT1Eqn ( - fvm::laplacian(-M1, T2)  + S1 );`
or should it be `auto T2InT1Eqn ( fvm::laplacian(-M1, T2)  + S1 );`

I was under the impression I need to insert the opposite of sign of the coupled terms.

**Comment by FoamScience** [comment]
Thanks for the super-quick reply.

1. The time derivative of the 2nd eq is indeed in "T1"
2. No additional coupling terms in S1 and S2. They are matrices for T2

Should S1 in `T2InT1Eqn` have a negative sign? `auto T2InT1Eqn ( - fvm::laplacian(-M1, T2)  - S1 );`?
or should it be `auto T2InT1Eqn ( fvm::laplacian(-M1, T2)  + S1 );`

I was under the impression I need to insert the opposite of sign of the coupled terms.

**Comment by fppimenta** [comment]
When the equations are equated to 0 on the same side, they should be inserted as they are written, as in your case.

I was asking about the source terms, because you may achieve additional implicit coupling through them.

**Comment by FoamScience** [comment]
Thanks for clarifying things; I must have messed with something else then. I'll have to debug the coupled system :)

Yes, I know about coupling the source terms (some experience from foam-extend), in my case though, they both depend on T2 only but I would love to find examples on how to achieve implicit coupling through them (would be useful for future equations).
The rheo* solvers don't seem to present examples.

**Comment by fppimenta** [comment]
The Nernst-Planck equations are the closer I can see in rheoTool from your case. Take a look at this (you will find theory in the user-guide; you can also check the signs of these equations):
 
https://github.com/fppimenta/rheoTool/tree/master/of70/src/libs/EDFModels/models/NernstPlanck/NernstPlanckCoupled

There are additional cases of coupling, but they are more complex and related with new operators. The theory is here: https://www.sciencedirect.com/science/article/abs/pii/S0045793019302427 and you can find the code in the repo (look inside classes, not only inside solvers).

Re-open issue if needed.

**Comment by FoamScience** [comment]
Hi again,

So, I was apparently able to fix some bugs in my code and it now works as expected.

However, the coupled solver seem to have no advantage over the segregated one (No improvement in possible timeSteps at all) and the problem is probably related to the fact that I can't change Petsc KSP and PC settings from the default ones!!

I compiled Petsc with the following configuration:
```bash
./configure \
    --with-debugging=0 --force \
    --with-mpi-lib=\[$MPI_ARCH_PATH/lib/libmpi.so\] \
    --with-mpi-include=\[$MPI_ARCH_PATH/include\] \
    --with-precision=double --with-shared-libraries=1 --with-scalar-type=real \
    --with-fc=$mpiFort --with-cc=$mpiCC --with-cxx=$mpiCXX \
    CXX_LINKER_FLAGS=-Wl,--no-as-needed \
    CFLAGS="-g -O2 -fPIC -fstack-protector-strong -Wformat -Werror=format-security" \
    CXXFLAGS="-g -O2 -fPIC -fstack-protector-strong -Wformat -Werror=format-security" \
    FCFLAGS="-g -O2 -fstack-protector-strong" \
    FFLAGS="-g -O2 -fstack-protector-strong" \
    CPPFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2" \
    LDFLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro" MAKEFLAGS=w
```

In the code, the solver is created with:
```cpp
    auto cs = autoPtr<coupledSolver>
    (
        new coupledSolver("pSc" , mesh.name() , runTime, mesh.solutionDict())
    );
```

And in `system/fvSolution` I accept default options
```cpp
coupledSolvers
{
     pSw {}
}
```

But in `system/petscDict`, any changes to `ksp_type` and the like doesn't take effect:
```bash
# This works!
-info
-options_view

# But these have no effect apparently
-pSc_ksp_type ibcgs
-region0_pSc_ksp_type ibcgs
-pSc_ksp_max_it 2000
-pSc_ksp_rtol 1e-5
-pSc_ksp_atol 0
-pSc_ksp_divtol 10
```

Despite the changes I make to these settings (I also tried prefixing things with region name), the solver always says:
```
Coupled system: water.alpha, p
Petsc:gmres:ilu: Solving coupled for water.alpha, Initial residual = 0.578137, Final residual = 4.17143e-12, No Iterations 1
Petsc:gmres:ilu: Solving coupled for p, Initial residual = 0.0109865, Final residual = 4.80165e-14, No Iterations 1
```

> I can also verify that this doesn't happen with your solvers and tutorials (Compiled with your scripts on a different machines) 
> using the same version of Petsc I'm using (3.14.0). So, I must be doing something flaky, right?
