### ISSUE TITLE
Problem to Compile Rheotool 

### ISSUE THREAD

**Issue by jcbottino** [fppimenta/rheoTool#39]
**Hello, I have a problem with the ./Allwmake command. When I run it, it gives this error:**

Allwmake /home/jcbottino/rheoTool-master/of70/src
Allwmake /home/jcbottino/rheoTool-master/of70/src/libs
+ wmake libso fvmb
wmake libso fvmb
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=64 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/home/jcbottino/OpenFOAM/OpenFOAM-7/src/finiteVolume/lnInclude -I/home/jcbottino/OpenFOAM/OpenFOAM-7/src/meshTools/lnInclude -IlnInclude -I. -I/home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude -I/home/jcbottino/OpenFOAM/OpenFOAM-7/src/OSspecific/POSIX/lnInclude   -fPIC -c operators/blockOperators.C -o Make/linux64GccDPInt64Opt/operators/blockOperators.o
In file included from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/List.H:316:0,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/HashTable.C:30,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/HashTable.H:566,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/NamedEnum.H:38,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/IOobject.H:79,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/regIOobject.H:41,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/GeometricField.H:42,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/GeometricScalarField.H:38,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/GeometricFields.H:34,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/finiteVolume/lnInclude/volFields.H:37,
                 from operators/div.H:39,
                 from operators/blockOperators.H:39,
                 from operators/blockOperators.C:26:
/home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/List.C: In instantiation of ‘Foam::List<T>::List(InputIterator, InputIterator) [with InputIterator = int; T = long int]’:
operators/div.C:147:20:   required from here
/home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/List.C:211:39: error: no matching function for call to ‘distance(int&, int&)’
     List<T>(first, last, std::distance(first, last))
                          ~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from /usr/include/c++/6/bits/stl_algobase.h:66:0,
                 from /usr/include/c++/6/bits/char_traits.h:39,
                 from /usr/include/c++/6/string:40,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/string.H:51,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/word.H:42,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/fileName.H:48,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/IOobject.H:75,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/regIOobject.H:41,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/GeometricField.H:42,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/GeometricScalarField.H:38,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/GeometricFields.H:34,
                 from /home/jcbottino/OpenFOAM/OpenFOAM-7/src/finiteVolume/lnInclude/volFields.H:37,
                 from operators/div.H:39,
                 from operators/blockOperators.H:39,
                 from operators/blockOperators.C:26:
/usr/include/c++/6/bits/stl_iterator_base_funcs.h:135:5: note: candidate: template<class _InputIterator> typename std::iterator_traits<_Iterator>::difference_type std::distance(_InputIterator, _InputIterator)
     distance(_InputIterator __first, _InputIterator __last)
     ^~~~~~~~
/usr/include/c++/6/bits/stl_iterator_base_funcs.h:135:5: note:   template argument deduction/substitution failed:
/usr/include/c++/6/bits/stl_iterator_base_funcs.h: In substitution of ‘template<class _InputIterator> typename std::iterator_traits<_Iterator>::difference_type std::distance(_InputIterator, _InputIterator) [with _InputIterator = int]’:
/home/jcbottino/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/List.C:211:39:   required from ‘Foam::List<T>::List(InputIterator, InputIterator) [with InputIterator = int; T = long int]’
operators/div.C:147:20:   required from here
/usr/include/c++/6/bits/stl_iterator_base_funcs.h:135:5: error: no type named ‘difference_type’ in ‘struct std::iterator_traits<int>’
make: *** [/home/jcbottino/OpenFOAM/OpenFOAM-7/wmake/rules/General/transform:26: Make/linux64GccDPInt64Opt/operators/blockOperators.o] Error 1



**I use Ubuntu 20.04 and g++ 6.4.0**

**Comment by fppimenta** [comment]
This issue seems to be equal to that one https://github.com/fppimenta/rheoTool/issues/28#issue-701164864. My answer is also the  same: I cannot reproduce that error. Rheotool (of70) does compile without problems in a fresh install of ubuntu 20.04. That gcc is somewhat old and could be the reason. Try updating it. However, if you were able to compile openfoam from source with that gcc, then it is unlikely the source of the problem.

**Comment by jcbottino** [comment]
I was using the current gcc 9.3.0.
I tried to downgrade to see if it worked.
Thanks for answering.

**Comment by jcbottino** [comment]
**I managed to run the Alwmake file and compiled it without a problem. It's just an installation error, I reinstalled the OF and it worked fine.
But now I have another problem, when executing the **rheFoam** command.**

rheoFoam: error while loading shared libraries: libpetsc.so.3.13: cannot open shared object file: No such file or directory

**What can I do? I would be grateful for the help**

**Comment by fppimenta** [comment]
The errors means that Petsc libs cannot be found. If the installation run without complaints, then this should be due to your LD_LIBRARY_PATH. Do you have aliases for different openfoam versions?

**Comment by jcbottino** [comment]
No I just have this ...

**if it helps, here is written in bashrc:**

export EIGEN_RHEO=/home/jcbottino/OpenFOAM/jcbottino-7/ThirdParty/Eigen3.2.9
export PETSC_DIR=/home/jcbottino/OpenFOAM/jcbottino-7/ThirdParty/petsc-3.13.3 
export PETSC_ARCH=arch-linux2-c-opt export LD_LIBRARY_PATH=$PETSC_DIR/$PETSC_ARCH/lib:$LD_LIBRARY_PATH

**Comment by fppimenta** [comment]
In  the last line of your .bashrc you should split the commands into two individual lines:

export PETSC_ARCH=arch-linux2-c-opt 
export LD_LIBRARY_PATH=$PETSC_DIR/$PETSC_ARCH/lib:$LD_LIBRARY_PATH

That should do the trick.

**Comment by jcbottino** [comment]
Great! Everything is running perfect.
Thank you fppimenta.
