### ISSUE TITLE
Error while compiling rheotool "Foam::coupledPolyPatch::transformType’ has not been declared"

### ISSUE THREAD

**Issue by BhargavAero** [fppimenta/rheoTool#43]
Hello, it would be greatly helpful if someone solve the issue.

[Ubuntu 20.04 & OpenFOAM-dev]
While following the installation guide of rheoTool, I have successfully downloaded and installed Eigen and Petsc. And they've also been sourced in the bashrc. 

Following the fourth step which is to compile the rheotool, there has been a following error

Make/linux64GccDPInt32Opt/files:37: *** missing separator.  Stop.
Make/linux64GccDPInt32Opt/files:37: *** missing separator.  Stop.

I have added missing separator "SOURCE += " before coupled/coupledSolver.C (line 37) in 
rheoTool-master/of70/src/libs/sparseMatrixSolvers/Make/linux64GccDPInt32Opt/files.
Sequentially the error was corrected and the following error appeared

segregated/hypreSolver/hypreSolver.C:159:31: error: ‘Foam::coupledPolyPatch::transformType’ has not been declared
  159 |             coupledPolyPatch::transformType::ROTATIONAL
      |                               ^~~~~~~~~~~~~
segregated/hypreSolver/hypreSolver.C:176:31: error: ‘Foam::coupledPolyPatch::transformType’ has not been declared
  176 |             coupledPolyPatch::transformType::ROTATIONAL
      |                               ^~~~~~~~~~~~~
segregated/hypreSolver/hypreSolver.C:192:31: error: ‘Foam::coupledPolyPatch::transformType’ has not been declared
  192 |             coupledPolyPatch::transformType::ROTATIONAL
      |                               ^~~~~~~~~~~~~
segregated/hypreSolver/hypreSolver.C: In member function ‘void Foam::hypreSolver<Type>::computeAllocationHypre(Foam::fvMatrix<Type>&, const Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh>&)’:
segregated/hypreSolver/hypreSolver.C:734:53: error: ‘const class Foam::cyclicAMIPolyPatch’ has no member named ‘neighbPatch’
  734 |        const cyclicAMIPolyPatch& neicamipp = camipp.neighbPatch();
      |                                                     ^~~~~~~~~~~
segregated/hypreSolver/hypreSolver.C: In member function ‘void Foam::hypreSolver<Type>::assembleHypreAbx(hypre_IJMatrix_struct*&, hypre_IJVector_struct*&, hypre_IJVector_struct*&, Foam::fvMatrix<Type>&, const Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh>&, int, int)’:
segregated/hypreSolver/hypreSolver.C:1039:28: error: ‘Foam::coupledPolyPatch::transformType’ has not been declared
 1039 |          coupledPolyPatch::transformType::ROTATIONAL
      |                            ^~~~~~~~~~~~~
segregated/hypreSolver/hypreSolver.C:1090:51: error: ‘const class Foam::cyclicAMIPolyPatch’ has no member named ‘neighbPatch’
 1090 |      const cyclicAMIPolyPatch& neicamipp = camipp.neighbPatch();
      |                                                   ^~~~~~~~~~~
segregated/hypreSolver/hypreSolver.C: In member function ‘void Foam::hypreSolver<Type>::assembleHypreBx(hypre_IJVector_struct*&, hypre_IJVector_struct*&, Foam::fvMatrix<Type>&, const Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh>&, int)’:
segregated/hypreSolver/hypreSolver.C:1287:30: error: ‘Foam::coupledPolyPatch::transformType’ has not been declared
 1287 |            coupledPolyPatch::transformType::ROTATIONAL
      |                              ^~~~~~~~~~~~~
make: *** [/opt/openfoam-dev/wmake/rules/General/transform:26: Make/linux64GccDPInt32Opt/segregated/hypreSolver/hypreSolvers.o] Error 1

Thank you!!

**Comment by fppimenta** [comment]
RheoTool is still not compatible with Openfoam v8, nor the dev branch you are using. Just downgrade to openfoam 7.0 and it will work.

**Comment by BhargavAero** [comment]
Thank you so much!!
The issue has been resolved. Yes, rheotool has been installed successfully with regard to openfoam7.
I am very grateful for your quickest reply.
