### ISSUE TITLE
Help! Error loading libHYPRE-2.18.2.

### ISSUE THREAD

**Issue by thiagostellin** [fppimenta/rheoTool#48]
I am facing the following problem:

"rheoFoam: error while loading shared libraries: libHYPRE-2.18.2.so: cannot open shared object file: No such file or directory"

Anyone has a clue on how may I solve it?

Thanks in advance.

**Comment by fppimenta** [comment]
If the installation was successful, then your issue is likely the same as here: https://github.com/fppimenta/rheoTool/issues/22#issuecomment-632964664

**Comment by thiagostellin** [comment]
Hello Prof. Pimenta, thanks for the prompt reply! In fact, after sending my issue I talked to a colleague who identified a missing ' in my .bashrc file. This one after the PATH word. Now I can proceed with the tutorials. Thanks a lot!
![WhatsApp Image 2021-04-13 at 17 43 25](https://user-images.githubusercontent.com/75186419/114618620-ef082480-9c7f-11eb-9790-bcb58a04a74f.jpeg)
