### ISSUE TITLE
arm compiler compilation

### ISSUE THREAD

**Issue by connorourke** [fppimenta/rheoTool#51]
When trying to compile with the arm compilers, after a successful OpenFOAM v7 build, I get errors of the  following type when trying to compile `LMatrixs.C` in `/lib/fvmb/` (the LMatrixs.C src compiles fine with gcc) :

`LMatrixs.C:38:1: error: cannot define or redeclare 'registerDebugSwitch' here because namespace 'fvmb' does not enclose namespace 'RegisterDebugSwitch<Foam::fvmb::LMatrix<double> >'
defineTemplateTypeNameAndDebug(LMatrix<scalar>, 0);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lustre/home/ba-corourke/bin/XCI/BUILD_FOAM_TEST/ARM/OpenFOAM-7/src/OpenFOAM/lnInclude/className.H:131:5: note: expanded from macro 'defineTemplateTypeNameAndDebug'
    defineTemplateTypeNameAndDebugWithName(Type, #Type, DebugSwitch)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lustre/home/ba-corourke/bin/XCI/BUILD_FOAM_TEST/ARM/OpenFOAM-7/src/OpenFOAM/lnInclude/className.H:126:5: note: expanded from macro 'defineTemplateTypeNameAndDebugWithName'
    defineTemplateDebugSwitchWithName(Type, Name, DebugSwitch)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lustre/home/ba-corourke/bin/XCI/BUILD_FOAM_TEST/ARM/OpenFOAM-7/src/OpenFOAM/lnInclude/defineDebugSwitch.H:119:5: note: expanded from macro 'defineTemplateDebugSwitchWithName'
    registerTemplateDebugSwitchWithName(Type, Name)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/lustre/home/ba-corourke/bin/XCI/BUILD_FOAM_TEST/ARM/OpenFOAM-7/src/OpenFOAM/lnInclude/defineDebugSwitch.H:78:42: note: expanded from macro 'registerTemplateDebugSwitchWithName'
        Foam::RegisterDebugSwitch<Type>::registerDebugSwitch(Name)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
LMatrixs.C:39:1: error: cannot define or redeclare 'registerDebugSwitch' here because namespace 'fvmb' does not enclose namespace 'RegisterDebugSwitch<Foam::fvmb::LMatrix<Foam::Vector<double> > >'
'`

Arm compiler version 20.0 (build number 51) (based on LLVM 9.0.1)

**Comment by fppimenta** [comment]
The only compiler tested is gcc and that's the only one for which I can provide support. 

A similar question was raised some time ago and I guess there should be a fork compatible with that compiler (see this https://github.com/fppimenta/rheoTool/pull/42#issue-588630654 and this https://github.com/BrushXue/rheoTool/tree/Mac). Note: I didn't test it and I cannot provide help for that, as I don't have such processors/compilers at hand.

**Comment by connorourke** [comment]
Great - thanks for the heads up.
