### ISSUE TITLE
How to simulate deformable drop with electrical bodyforce?

### ISSUE THREAD

**Issue by Pintu0101** [fppimenta/rheoTool#6]
Rheo-interfoam can only account for multi phase flow. How to add the electrical body force to the solver and  surface charge to the drop in a multi-phase platform.

**Comment by fppimenta** [comment]
You would need to create a new EDFmodel, probably the Taylor-Melcher leaky dielectric model. This model was released as 'untested' in a previous version, but has been removed meanwhile. I already did it some time ago, but VOF was having troubles in keeping the phases immiscible for long time simulations. Probably the easiest is to try a solver which is already doing this for GNF fluids (not part of rheoTool): http://openfoamwiki.net/index.php/Contrib/EHDFoam. That solver should do what you want, or, at least, it will be a good starting point.

**Comment by Pintu0101** [comment]
Thanks for your reply sir..Can't we modify the inter-foam solver to add the electric body force term. I am new to openfoam and learning from the source code you have provided.

**Comment by fppimenta** [comment]
Yes you can start with interFoam and add the force term to it, but before that you need to define your force term and this is where you need to implement the EHD model. You can do everything in the same executable, without libs, if you want to make it easier. Although it is quite easy to implement the equations (making VOF work effectively is a different story), if your are beginning with openfoam it can be tricky. That is why I suggested solver EHDFoam, which seems to be ready-to-use (I don't tested it) and do what you need.
