### ISSUE TITLE
Error when compiling the program

### ISSUE THREAD

**Issue by mikewang2000** [fppimenta/rheoTool#7]
I tried to compile rheoTool with OpenFoam v4.1 on CentOS 7.x, but it failed in the linking stage for solvers/rheoFoam and solvers/rheoInterFoam:
-lm -o /mnt/data1/users/software/OpenFoam/rheoTool/of40/src/build/bin/rheoFoam
/usr/bin/ld: warning: libEDFModels.so, needed by /mnt/data1/users/software/OpenFoam/rheoTool/of40/src/build/lib/libBCRheoTool.so, not found (try using -rpath or -rpath-link)
/mnt/data1/users/software/OpenFoam/rheoTool/of40/src/build/lib/libpostProcessingRheoTool.so: undefined reference to `Foam::EDFEquation::FK_'
/mnt/data1/users/software/OpenFoam/rheoTool/of40/src/build/lib/libBCRheoTool.so: undefined reference to `Foam::EDFEquation::eK_'
/mnt/data1/users/software/OpenFoam/rheoTool/of40/src/build/lib/libBCRheoTool.so: undefined reference to `Foam::EDFEquation::kbK_'
collect2: error: ld returned 1 exit status
make: *** [/mnt/data1/users/software/OpenFoam/rheoTool/of40/src/build/bin/rheoFoam] Error 1

It appears in solvers/rheoFoam/Make/options and solvers/rheoInterFoam/Make/options EDFModels library link option and include path are not specified. 

Adding the path and libray linkng options has fixed the problem:
cp solvers/rheoEFoam/Make/options solvers/rheoFoam/Make/options
sed -i.back -e 's!postProcessing/postProcUtils/lnInclude!postProcessing/postProcUtils/lnInclude -I../../libs/EDFModels/lnInclude!' -e 's!-lpostProcessingRheoTool!-lpostProcessingRheoTool -L$(FOAM_USER_LIBBIN) -lEDFModels!' solvers/rheoInterFoam/Make/options

**Comment by fppimenta** [comment]
Did you modified the code for these solvers before compiling, or the errors happen for the original code as provided in the repo?

**Comment by mikewang2000** [comment]
No, I have not modified the code. I simply downloaded the code yesterday/today:
git clone https://github.com/fppimenta/rheoTool

**Comment by fppimenta** [comment]
Well that's strange. It works on red hat and I guess other persons get it installed in centos also. Our tests are exclusively in Ubuntu OS. The error is in fact related with ld and its need to know where to find libEDFModels.so. That lib is not directly used by those two solvers, but is needed as dependency of the BC lib. It seems your ld is behaving differently regarding other OS (perhaps a version or flag issue).
Anyway, thanks for the warning.
