### ISSUE TITLE
heat transfer in two-phase flows

### ISSUE THREAD

**Issue by Joe199999** [fppimenta/rheoTool#73]
Hi Dr. pimenta

I found that there is no solver to solve the energy eqn in the two-phase flow of non-Newtonian fluids in rheoTool. So, I added the modified "correct" function, which is used in rheoHeatFoam, to rheoInterHeatFoam (new solver) and created the "thermo" object according to the "fluidThermoMixtureModel" class. But this class just has the "isotropic" and "frozenTemperature" models for heat transfer. The  "isotropic" model does not consider convective terms of the energy equation, according to the user guide. Can I add the Boussinesq model to the  "fluidThermoMixtureModel" class?

Thank you in advance

**Comment by fppimenta** [comment]
Everything concerning two-phase flows in rheoTool is still experimental and under-development. That it is why rheoInterHeatFoam was not added as solver when we added thermo features in the last release, although all the machinery needed was made ready (e.g. fluidThermoMixtureModel, among others). You can add anything on your own, as long as you know what you are doing.
