### ISSUE TITLE
About some definition and dimensions in Rheotool

### ISSUE THREAD

**Issue by Pintu0101** [fppimenta/rheoTool#8]
Sir,  I think there is some incorrect definitions and dimensions in rheoTool appendix A. Please look into the matter and clarify those.
1. u· S = phi [0 3 -1 0 0 0 0] Face fluxes (scalar) I think this one should be phi= rho*U for incompressible flow and U for incompressible flow.
2. F = FK_ [0 0 1 0 -1 1 0] Faraday’s constant (scalar) its dimension is not correct i think it should be [0 0 0 0 -1 1 0] 
3. e = eK_ [0 0 1 0 0 1 0] Elementary charge (scalar)   its dimension is not correct also it should be [0 0 0 0 0 1 0]

Waiting for your reply..

**Comment by fppimenta** [comment]
Guess all is correct.

1- In createPhi.H, phi is initiated as fvc::flux(U) and fvc::flux(U) is dotInterpolate(vvf.mesh().Sf(), U). If you have doubts check the units in the header of the phi files written to the run directory. Even for multiphase flow phi is like that (you then have a rhoPhi which is different).

2- F is C/mol = A s / mol. Check this: https://cfd.direct/openfoam/user-guide/v6-basic-file-format/ and compare. 

3- e is C = A s. Check this: https://cfd.direct/openfoam/user-guide/v6-basic-file-format/ and compare.

**Comment by Pintu0101** [comment]
Sir, thanks for your reply. Then  these two terms are dimensionally inconsistent?   fvm::ddt(U) + fvm::div(phi, U)

**Comment by fppimenta** [comment]
No they are not. The equation is being integrated in space (volume)... Guess you are missing some openfoam basics.
