### ISSUE TITLE
Error while compiling a new constitutiveEquation 

### ISSUE THREAD

**Issue by subhamkd** [fppimenta/rheoTool#81]
Hi,

I am trying to compile a new constitutive equation in of7 following the procedure in the user guide, but after copying a preexisting model, renaming it and running the Allwmake script in the src folder, I am getting a long list of errors saying 

```/home/subham/anaconda3/lib/libtinfo.so.6: no version information available (required by /bin/bash)``` 

and the new model is not compiling. Can anyone tell me what can possibly be wrong?

I am using openfoam 7 in ubuntu 20.04.

Thanks

**Comment by fppimenta** [comment]
You need to show the full error message. That's not enough to debug.

**Comment by subhamkd** [comment]
![Screenshot from 2022-03-11 13-42-16](https://user-images.githubusercontent.com/65963454/157959973-bf22cd00-41d8-4521-9a88-302256bb491a.png)
This is the complete error message

**Comment by subhamkd** [comment]
Hi, Sorry about that, I solved the problem. Looks like these errors are not affecting the compilation of the new constitutive equation, it was something else.
Thank you.
